version: '2'
services:
  cellconfig:
    build: ./cellconfig
    ports:
    - "7000:7000"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
  node1:
    build: ./node
    networks:
      app_net:
        ipv4_address: 172.16.238.100
  node2:
    build: ./node
    networks:
      app_net:
        ipv4_address: 172.16.238.101
  node3:
    build: ./node
    networks:
      app_net:
        ipv4_address: 172.16.238.102

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
